### ISSUE TITLE
Hello I'm having the problem while running your sample code

### ISSUE THREAD

**Issue by davies1828** [HSAFoundation/HSA-Runtime-Reference-Source#3]
I run the sample program and it shows the following message
![screenshot from 2014-12-02 14 46 07](https://cloud.githubusercontent.com/assets/9927508/5259297/2f77fa88-7a39-11e4-9da5-eaee5999272e.png)

the status error code is added by myself to show the status and it comes HSA_STATUS_ERROR

I find out the problem is in file hsa_code_unit.cpp 
if (HSA_EXT_AMD_CODE_VERSION_MAJOR != akc->amd_code_version_major)

the version dont matchs so that's why it return ERROR

is there anything I do wrong?

any comment will be appreciated

**Comment by cwhuang888** [comment]
Really sorry of responding late.
@tstellarAMD , the error message when running the original compile script is

WARNING: Linking two modules of different target triples: /usr/local/lib/clc/kaveri-r600--.bc' is 'r600--' whereas 'llvm-link' is 'r600--amdhsa-amdgpu'

I recompiled using clang version 3.6.0
clang version 3.6.0 (http://llvm.org/git/clang.git 0ee66aad3e44d03c6e9c3fd8a5aaafde89028d94) (http://llvm.org/git/llvm.git 41bda9f2019ecc2e2b26cef6735d19c108ac4d07)

The output of running MatMul is still the same :-(
Using agent: Spectre
Loaded ELF successfully.
Failed getting code unit information.
Failed compiling the kernel
: Success

**Comment by tstellarAMD** [comment]
Can you post the generated .o file?

**Comment by cwhuang888** [comment]
MatMul.o
![screenshot from 2015-01-09 14 43 50](https://cloud.githubusercontent.com/assets/9817751/5676350/45fb8f24-980f-11e4-90a1-97b6bbbbc2bd.png)
![screenshot from 2015-01-09 14 44 00](https://cloud.githubusercontent.com/assets/9817751/5676351/45fdecd8-980f-11e4-9266-9345e83fabf0.png)

MatMul.cl.o
![screenshot from 2015-01-09 14 48 11](https://cloud.githubusercontent.com/assets/9817751/5676361/6fee5da2-980f-11e4-8708-c0d9d5c01ea3.png)
![screenshot from 2015-01-09 14 48 17](https://cloud.githubusercontent.com/assets/9817751/5676362/6ffaf152-980f-11e4-8353-884fa76db67b.png)

Not sure why there are mixed strings of clang 3.6.0 together with clang 3.5.0, perhaps anything wrong ?

**Comment by tstellarAMD** [comment]
Can you post the actual object file instead of a screenshot of it.

**Comment by cwhuang888** [comment]
Sorry that i don't know how to directly attach the object file here.
Please use the following links

main.o
https://www.dropbox.com/s/ydcmfosyqyaumcu/main.o?dl=0

MatMul.cl.o
https://www.dropbox.com/s/6zoh7ha39nm2hxw/MatMul.cl.o?dl=0

MatMul.o
https://www.dropbox.com/s/7o5ekw568pos4da/MatMul.o?dl=0

Thanks for helping out !
