### ISSUE TITLE
Support for CPU

### ISSUE THREAD

**Issue by chishengshih** [HSAFoundation/HSA-Runtime-Reference-Source#6]
Hi, 

We tried to revise the example to use CPU. However, the application is stalled at wating the signal from execution. After studing the source code, it seems that amd_hw_aql_command_processor only implements the operations for GPU, not CPU. Is it correct? If yes, do you plan to add the support later?

**Comment by jedwards-AMD** [comment]
There are no immediate plans to support kernel dispatch on the AMD CPU device. However, the CPU is considered and agent, and fully participates in the coherent memory model in this implementation.
