### ISSUE TITLE
LICENSE.txt and source files' headers give conflicting information

### ISSUE THREAD

**Issue by kaol** [HSAFoundation/HSA-Runtime-Reference-Source#7]
The license given in LICENSE.txt is a standard three clause BSD license.  The newer source files included in the repository have that at the top of the file, but most of the files have something else. It would be simpler if every source file had the same license header as the new files use.

There's one hard issue with the older license header text: "You agree that you will not reverse engineer or decompile the Materials, in whole or in part, except as allowed by applicable law." This clause makes little sense since this repository includes no binary data in itself, nor any firmware code. Moreover, it is a blocker for getting this software included to Debian (the perspective I'm looking at this from). It's a requirement that there are no use restrictions on software included in Debian, including reverse engineering them. Even when it makes little sense to do it since it is compiled from source included in Debian.

**Comment by jedwards-AMD** [comment]
Thank you for your comment. We are discussing the issue with AMD legal and will provide a solution soon.

**Comment by kaol** [comment]
Looks like the version of runtime at https://github.com/RadeonOpenCompute/ROCR-Runtime has unified its license header practices. Thank you for looking into this.

**Comment by jedwards-AMD** [comment]
This will also be propagated to the HSA Foundation release with a new update.
