### ISSUE TITLE
Broken build in master branch

### ISSUE THREAD

**Issue by tstellarAMD** [HSAFoundation/HSA-Runtime-Reference-Source#8]
Hi,

I get the following error when trying to build the runtime source:

/usr/lib64/ccache/c++   -DHSA_EXPORT=1 -DHSA_EXPORT_FINALIZER=1 -DHSA_EXPORT_IMAGES=1 -DLITTLEENDIAN_CPU=1 -D__linux__ -Dhsa_runtime64_EXPORTS -std=c++11  -Werror -fexceptions -fno-rtti -fvisibility=hidden -Wno-error=sign-compare -Wno-sign-compare -Wno-write-strings -Wno-deprecated-declarations -Wno-conversion-null -fno-math-errno -fno-threadsafe-statics -fmerge-all-constants -fms-extensions -Wno-error=comment -Wno-comment -Wno-error=pointer-arith -Wno-pointer-arith -m64 -msse -msse2 -fPIC -I/home/tstellar/HSA-Runtime-Reference-Source/core/.. -I/home/tstellar/HSA-Runtime-Reference-Source/core/../inc -I/home/tstellar/HSA-Runtime-Reference-Source/core/inc -I/home/tstellar/HSA-Runtime-Reference-Source/core/tools/libamdhsacode -I/home/tstellar/HSA-Runtime-Reference-Source/core/tools/loader -I/home/tstellar/libhsakmt/hsakmt    -o CMakeFiles/hsa-runtime64.dir/runtime/amd_gpu_agent.cpp.o -c /home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp: In constructor ‘amd::GpuAgent::GpuAgent(HSAuint32, const HsaNodeProperties&, const std::vector<_HaCacheProperties>&)’:
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp:79:54: error: request for member ‘ui32’ in ‘node_props._HsaNodeProperties::EngineId’, which is of non-class type ‘const HSAuint32 {aka const unsigned int}’
   compute_capability_.Initialize(node_props.EngineId.ui32.Major,
                                                      ^
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp:80:54: error: request for member ‘ui32’ in ‘node_props._HsaNodeProperties::EngineId’, which is of non-class type ‘const HSAuint32 {aka const unsigned int}’
                                  node_props.EngineId.ui32.Minor,
                                                      ^
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp:81:54: error: request for member ‘ui32’ in ‘node_props._HsaNodeProperties::EngineId’, which is of non-class type ‘const HSAuint32 {aka const unsigned int}’
                                  node_props.EngineId.ui32.Stepping);
                                                      ^
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp: In member function ‘uint16_t amd::GpuAgent::GetMicrocodeVersion() const’:
/home/tstellar/HSA-Runtime-Reference-Source/core/runtime/amd_gpu_agent.cpp:449:32: error: request for member ‘ui32’ in ‘((const amd::GpuAgent*)this)->amd::GpuAgent::properties_._HsaNodeProperties::EngineId’, which is of non-class type ‘const HSAuint32 {aka const unsigned int}’
   return (properties_.EngineId.ui32.uCode);
                                ^
CMakeFiles/hsa-runtime64.dir/build.make:195: recipe for target 'CMakeFiles/hsa-runtime64.dir/runtime/amd_gpu_agent.cpp.o' failed

**Comment by tschwinge** [comment]
I've run into the same problem.  I tried building against <http://cgit.freedesktop.org/~gabbayo/libhsakmt/>, `libhsakmt-4.2` branch, commit 07ea8f02f3c3ac3a123acc3de5307fa8452a21c1.  Apparently, that is not supported.  Using instead <https://github.com/HSAFoundation/HSA-Drivers-Linux-AMD>, `master` branch, commit 7fb04c4da8b2b46078bf9330c798274f0d7a8c2b, `src/libhsakmt/` directory, the build went fine.

**Comment by jedwards-AMD** [comment]
This version of the runtime is not compatible with the cgit.freedesktop.org version. The associated CMakeLists.txt file has been changed to reflect that.
